// <auto-generated />
namespace demo.THR.Infraestrutura.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig_Carga_Inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_Carga_Inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201511151806523_mig_Carga_Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
